#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers
source ../settings/scripts/_ynh_mysql_dump_db.sh

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

ynh_backup --src_path="$install_dir"

ynh_backup --src_path="$data_dir" --is_big

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================
ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP LOGROTATE
#=================================================
ynh_print_info --message="Backing up logrotate..."

ynh_backup --src_path="/etc/logrotate.d/$app"

#=================================================
# BACKUP SYSTEMD CONFIGURATION
#=================================================
ynh_print_info --message="Backing up the systemd services conf files..."

ynh_backup --src_path="/etc/systemd/system/$app-redis.target"
ynh_backup --src_path="/etc/systemd/system/$app-web.target"
ynh_backup --src_path="/etc/systemd/system/$app-workers.target"
ynh_backup --src_path="/etc/systemd/system/$app.target"
ynh_backup --src_path="/etc/systemd/system/$app-redis-cache.service"
ynh_backup --src_path="/etc/systemd/system/$app-redis-queue.service"
ynh_backup --src_path="/etc/systemd/system/$app-frappe-default-worker.service"
ynh_backup --src_path="/etc/systemd/system/$app-frappe-long-worker.service"
ynh_backup --src_path="/etc/systemd/system/$app-frappe-short-worker.service"
ynh_backup --src_path="/etc/systemd/system/$app-frappe-schedule.service"
ynh_backup --src_path="/etc/systemd/system/$app-frappe-web.service"
ynh_backup --src_path="/etc/systemd/system/$app-node-socketio.service"

#=================================================
# BACKUP THE DATABASE
#=================================================
ynh_print_info --message="Backing up the mysql database..."

ynh_mysql_dump_db --database="$db_name" --default_character_set="utf8mb4" > db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."