#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Stopping a supervisor service..."

# ynh_supervisor_action --service="${app}-horizon" --action="stop" --log_path="/var/log/$app/${app}-horizon.log"

#ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# ...
#=================================================

chown -R $app:www-data "$install_dir"

#=================================================
# START SUPERVISOR SERVICE
#=================================================
ynh_script_progression "Starting a supervisor service..."

#ynh_supervisor_action --service="${app}-horizon" --action="start" --log_path="systemd" --wait_until="success: ${app}-horizon"

#ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
