#!/bin/bash

# This is the tutorial version of the app.
# It contains extra commands to explain what should be done in case you want to adjust some part of the script.
# Once you are done, you may remove them.

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

# Settings are automatically loaded as bash variables
# in every app script context, therefore typically these will exist:
# - $domain
# - $path
# - $language
# - $install_dir
# - $port
# ...

# For remove operations :
# - the core will deprovision every resource defined in the manifest **after** this script is ran
# this includes removing the install directory, and data directory (if --purge was used)

# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
yunohost service remove $app-node-socketio
yunohost service remove $app-frappe-web
yunohost service remove $app-frappe-schedule
yunohost service remove $app-frappe-short-worker
yunohost service remove $app-frappe-long-worker
yunohost service remove $app-frappe-default-worker
yunohost service remove $app-redis-queue
yunohost service remove $app-redis-cache

#=================================================
# STOP AND REMOVE SERVICES
#=================================================
ynh_script_progression --message="Stopping and removing systemd services..." --weight=2

# Remove the dedicated supervisor config
systemctl stop "$app.target" --quiet
systemctl disable "$app.target" --quiet
ynh_secure_remove --file="/etc/systemd/system/$app.target"

systemctl stop "$app-web.target" --quiet
systemctl disable "$app-web.target" --quiet
ynh_secure_remove --file="/etc/systemd/system/$app-web.target"
ynh_remove_systemd_config --service="$app-node-socketio"
ynh_remove_systemd_config --service="$app-frappe-web"

systemctl stop "$app-workers.target" --quiet
systemctl disable "$app-workers.target" --quiet
ynh_secure_remove --file="/etc/systemd/system/$app-workers.target"
ynh_remove_systemd_config --service="$app-frappe-schedule"
ynh_remove_systemd_config --service="$app-frappe-short-worker"
ynh_remove_systemd_config --service="$app-frappe-long-worker"
ynh_remove_systemd_config --service="$app-frappe-default-worker"

systemctl stop "$app-redis.target" --quiet
systemctl disable "$app-redis.target" --quiet
ynh_secure_remove --file="/etc/systemd/system/$app-redis.target"
ynh_remove_systemd_config --service="$app-redis-queue"
ynh_remove_systemd_config --service="$app-redis-cache"

systemctl daemon-reload

# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration..." --weight=1

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --weight=10

# Remove metapackage and its dependencies
ynh_remove_nodejs

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last