#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
yunohost service remove $app-node-socketio
yunohost service remove $app-frappe-web
yunohost service remove $app-frappe-schedule
yunohost service remove $app-frappe-short-worker
yunohost service remove $app-frappe-long-worker
yunohost service remove $app-frappe-default-worker
yunohost service remove $app-redis-queue
yunohost service remove $app-redis-cache

#=================================================
# STOP AND REMOVE SYSTEMD SERVICES
#=================================================
ynh_script_progression "Stopping and removing systemd services..."

# Remove the dedicated systemd config
systemctl stop "$app.target" --quiet
systemctl disable "$app.target" --quiet
ynh_safe_rm "/etc/systemd/system/$app.target"

systemctl stop "$app-web.target" --quiet
systemctl disable "$app-web.target" --quiet
ynh_safe_rm "/etc/systemd/system/$app-web.target"
ynh_config_remove_systemd "$app-node-socketio"
ynh_config_remove_systemd "$app-frappe-web"

systemctl stop "$app-workers.target" --quiet
systemctl disable "$app-workers.target" --quiet
ynh_safe_rm "/etc/systemd/system/$app-workers.target"
ynh_config_remove_systemd "$app-frappe-schedule"
ynh_config_remove_systemd "$app-frappe-short-worker"
ynh_config_remove_systemd "$app-frappe-long-worker"
ynh_config_remove_systemd "$app-frappe-default-worker"

systemctl stop "$app-redis.target" --quiet
systemctl disable "$app-redis.target" --quiet
ynh_safe_rm "/etc/systemd/system/$app-redis.target"
ynh_config_remove_systemd "$app-redis-queue"
ynh_config_remove_systemd "$app-redis-cache"

# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing dependencies..."

# Remove metapackage and its dependencies
uninstall_wkhtmltopdf_patched_qt_package

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
