#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing wkhtmltopdf patched qt package..."

# Install wkhtmltopdf patched qt package
install_wkhtmltopdf_patched_qt_package

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
ynh_script_progression "Restoring the MySQL database..."

ynh_mysql_db_shell < ./db.sql

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring the NGINX web server configuration..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE SYSTEMD CONFIGURATIONS
#=================================================
ynh_script_progression "Enable systemd services"

ynh_restore "/etc/systemd/system/$app-redis.target"
ynh_restore "/etc/systemd/system/$app-web.target"
ynh_restore "/etc/systemd/system/$app-workers.target"
ynh_restore "/etc/systemd/system/$app.target"
ynh_restore "/etc/systemd/system/$app-redis-cache.service"
ynh_restore "/etc/systemd/system/$app-redis-queue.service"
ynh_restore "/etc/systemd/system/$app-frappe-default-worker.service"
ynh_restore "/etc/systemd/system/$app-frappe-long-worker.service"
ynh_restore "/etc/systemd/system/$app-frappe-short-worker.service"
ynh_restore "/etc/systemd/system/$app-frappe-schedule.service"
ynh_restore "/etc/systemd/system/$app-frappe-web.service"
ynh_restore "/etc/systemd/system/$app-node-socketio.service"

systemctl daemon-reload

# Enable target systemd files
systemctl enable "$app-redis.target" --quiet
systemctl enable "$app-workers.target" --quiet
systemctl enable "$app-web.target" --quiet
systemctl enable "$app.target" --quiet

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add "$app-redis-cache" --description="$app redis cache service"
yunohost service add "$app-redis-queue" --description="$app redis queue service"
yunohost service add "$app-frappe-default-worker" --description="$app default worker service"
yunohost service add "$app-frappe-long-worker" --description="$app long worker service"
yunohost service add "$app-frappe-short-worker" --description="$app short worker service"
yunohost service add "$app-frappe-schedule" --description="$app schedule service"
yunohost service add "$app-frappe-web" --description="$app web service"
yunohost service add "$app-node-socketio" --description="$app node socketio service"

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting systemd services..."

# For some reason --wait_until makes starting of services very long during restore (compare to install script). Needs to be investigated later.

ynh_systemctl --service=$app-redis-cache --action="start" --log_path="$install_dir/dokos-bench-folder/logs/redis-cache.log" # --wait_until="Ready to accept connections"
ynh_systemctl --service=$app-redis-queue --action="start" --log_path="$install_dir/dokos-bench-folder/logs/redis-queue.log" # --wait_until="Ready to accept connections"
systemctl start "$app-redis.target" --quiet

ynh_systemctl --service=$app-frappe-default-worker --action="start" --log_path="$install_dir/dokos-bench-folder/logs/default-worker.log" # --wait_until="Listening on var-www-$app-dokos-bench-folder:default"
ynh_systemctl --service=$app-frappe-long-worker --action="start" --log_path="$install_dir/dokos-bench-folder/logs/long-worker.log" # --wait_until="Listening on var-www-$app-dokos-bench-folder:long"
ynh_systemctl --service=$app-frappe-short-worker --action="start" --log_path="$install_dir/dokos-bench-folder/logs/short-worker.log" # --wait_until="Listening on var-www-$app-dokos-bench-folder:short"
ynh_systemctl --service=$app-frappe-schedule --action="start" --log_path="systemd" --wait_until="Started dokos-frappe-schedule.service - "
systemctl start "$app-workers.target" --quiet

ynh_systemctl --service=$app-frappe-web --action="start" --log_path="systemd" --wait_until="Started dokos-frappe-web.service - "
ynh_systemctl --service=$app-node-socketio --action="start" --log_path="$install_dir/dokos-bench-folder/logs/node-socketio.log" # --wait_until="Realtime service listening on"
systemctl start "$app-web.target" --quiet

systemctl start "$app.target" --quiet

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading NGINX web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# SCHEDULER
#=================================================

# Enable and resume the scheduler for the site
ynh_script_progression "Enabling Scheduler..."

pushd $install_dir/dokos-bench-folder

    ynh_exec_as_app PATH=$install_dir/bin:$PATH bench --site $domain scheduler enable && \
    ynh_exec_as_app PATH=$install_dir/bin:$PATH bench --site $domain scheduler resume
popd

# Now to make sure the environment is fully setup
chmod 750 "$install_dir"
chown $app:$app -R $install_dir

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading NGINX web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Restoring the logrotate configuration..."

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
