#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SCHEDULER
#=================================================
ynh_script_progression "Activate maintenance mode."

pushd $install_dir/dokos-bench-folder

	# Activate maintenance mode.
	ynh_exec_as_app PATH=$install_dir/bin:$PATH bench --site $domain set-maintenance-mode on

	ynh_script_progression "Disabling Scheduler..."

	# Pause and disable the scheduler for the site

    ynh_exec_as_app PATH=$install_dir/bin:$PATH bench --site $domain scheduler pause && \
    ynh_exec_as_app PATH=$install_dir/bin:$PATH bench --site $domain scheduler disable && \
popd

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
yunohost service remove $app-node-socketio
yunohost service remove $app-frappe-web
yunohost service remove $app-frappe-schedule
yunohost service remove $app-frappe-short-worker
yunohost service remove $app-frappe-long-worker
yunohost service remove $app-frappe-default-worker
yunohost service remove $app-redis-queue
yunohost service remove $app-redis-cache

#=================================================
# STOP SYSTEMD SERVICES
#=================================================
ynh_script_progression "Stopping systemd services..."

ynh_systemctl --service=$app --action="stop"

systemctl stop "$app.target" --quiet
systemctl stop "$app-web.target" --quiet
ynh_systemctl --service="$app-node-socketio" --action="stop" --log_path="$install_dir/dokos-bench-folder/logs/node-socketio.log"
ynh_systemctl --service="$app-frappe-web" --action="stop" --log_path="$install_dir/dokos-bench-folder/logs/web.log"

systemctl stop "$app-workers.target" --quiet
ynh_systemctl --service="$app-frappe-schedule" --action="stop" --log_path="$install_dir/dokos-bench-folder/logs/schedule.log"
ynh_systemctl --service="$app-frappe-short-worker" --action="stop" --log_path="$install_dir/dokos-bench-folder/logs/short-worker.log"
ynh_systemctl --service="$app-frappe-long-worker" --action="stop" --log_path="$install_dir/dokos-bench-folder/logs/long-worker.log"
ynh_systemctl --service="$app-frappe-default-worker" --action="stop" --log_path="$install_dir/dokos-bench-folder/logs/default-worker.log"

systemctl stop "$app-redis.target" --quiet
ynh_systemctl --service="$app-redis-queue" --action="stop" --log_path="$install_dir/dokos-bench-folder/logs/redis-queue.log"
ynh_systemctl --service="$app-redis-cache" --action="stop" --log_path="$install_dir/dokos-bench-folder/logs/redis-cache.log"

#=================================================
# "REBUILD" THE APP (DEPLOY NEW SOURCES, RERUN NPM BUILD...)
#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing wkhtmltopdf patched qt package..."

# Install wkhtmltopdf patched qt package
install_wkhtmltopdf_patched_qt_package

ynh_script_progression "Updating NodeJS..."

# Update yarn
ynh_script_progression "Installing yarn..."

pushd $install_dir
    corepack enable
    ynh_hide_warnings corepack prepare yarn@latest --activate
    ynh_hide_warnings ynh_exec_as_app yarn install --network-timeout=100000
popd

# Install virtualenv if it doesn't exist
python3 -m venv $install_dir

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Upgrading source files..."

ynh_exec_as_app $install_dir/bin/python -m pip install --upgrade dokos-cli

pushd $install_dir/dokos-bench-folder
    # Setup Python's virtual environment for your bench. This sets up a env folder under the root of the bench directory.
	ynh_exec_as_app PATH=$install_dir/bin:$PATH bench setup env
	# Generate or over-write sites/common_site_config.json
   	ynh_config_add --template="common_site_config.json" --destination="$install_dir/dokos-bench-folder/sites/common_site_config.json"
	# Generates configuration for Redis
	ynh_config_add --template="redis_queue.conf" --destination="$install_dir/dokos-bench-folder/config/redis_queue.conf"
	ynh_config_add --template="redis_cache.conf" --destination="$install_dir/dokos-bench-folder/config/redis_cache.conf"
	# Generate Procfile for bench start
	ynh_safe_rm "$install_dir/dokos-bench-folder/Procfile"
	ynh_exec_as_app PATH=$install_dir/bin:$PATH bench setup procfile
	# Setup node dependencies for socketio server
	ynh_exec_as_app PATH=$install_dir/bin:$PATH bench setup socketio
popd

ynh_script_progression "Installing Dodock (frappe), it can take quiet some time..."

upgrade_app_to_bench frappe

ynh_script_progression "Installing $app..."

upgrade_app_to_bench erpnext

ynh_script_progression "Installing $app applications payments..."

upgrade_app_to_bench payments

ynh_script_progression "Installing $app applications hrms..."

upgrade_app_to_bench hrms

chmod 750 "$install_dir"
chown -R $app: "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SYSTEMD CONFIGURATION
#=================================================
ynh_script_progression "Adding systemd configurations related to $app..."

### `ynh_systemd_config` is used to configure a systemd script for an app, using the conf/systemd.service template
ynh_config_add --template="frappe-bench-redis.target" --destination="/etc/systemd/system/$app-redis.target"
ynh_config_add --template="frappe-bench-web.target" --destination="/etc/systemd/system/$app-web.target"
ynh_config_add --template="frappe-bench-workers.target" --destination="/etc/systemd/system/$app-workers.target"
ynh_config_add --template="frappe-bench.target" --destination="/etc/systemd/system/$app.target"

# Create a dedicated systemd config
ynh_config_add_systemd --service="$app-redis-cache" --template="frappe-bench-redis-cache.service"
ynh_config_add_systemd --service="$app-redis-queue" --template="frappe-bench-redis-queue.service"
ynh_config_add_systemd --service="$app-frappe-default-worker" --template="frappe-bench-frappe-default-worker.service"
ynh_config_add_systemd --service="$app-frappe-long-worker" --template="frappe-bench-frappe-long-worker.service"
ynh_config_add_systemd --service="$app-frappe-short-worker" --template="frappe-bench-frappe-short-worker.service"
ynh_config_add_systemd --service="$app-frappe-schedule" --template="frappe-bench-frappe-schedule.service"
ynh_config_add_systemd --service="$app-frappe-web" --template="frappe-bench-frappe-web.service"
ynh_config_add_systemd --service="$app-node-socketio" --template="frappe-bench-node-socketio.service"

systemctl daemon-reload

# Enable target systemd files
systemctl enable "$app-redis.target" --quiet
systemctl enable "$app-workers.target" --quiet
systemctl enable "$app-web.target" --quiet
systemctl enable "$app.target" --quiet

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add "$app-redis-cache" --description="$app redis cache service"
yunohost service add "$app-redis-queue" --description="$app redis queue service"
yunohost service add "$app-frappe-default-worker" --description="$app default worker service"
yunohost service add "$app-frappe-long-worker" --description="$app long worker service"
yunohost service add "$app-frappe-short-worker" --description="$app short worker service"
yunohost service add "$app-frappe-schedule" --description="$app schedule service"
yunohost service add "$app-frappe-web" --description="$app web service"
yunohost service add "$app-node-socketio" --description="$app node socketio service"

#=================================================
# RESTART SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting systemd services..."

ynh_systemctl --service=$app-redis-cache --action="restart" --log_path="$install_dir/dokos-bench-folder/logs/redis-cache.log" # --wait_until="Ready to accept connections"
ynh_systemctl --service=$app-redis-queue --action="restart" --log_path="$install_dir/dokos-bench-folder/logs/redis-queue.log" # --wait_until="Ready to accept connections"
systemctl restart "$app-redis.target" --quiet

ynh_systemctl --service=$app-frappe-default-worker --action="restart" --log_path="$install_dir/dokos-bench-folder/logs/default-worker.log" # --wait_until="Listening on var-www-$app-dokos-bench-folder:default"
ynh_systemctl --service=$app-frappe-long-worker --action="restart" --log_path="$install_dir/dokos-bench-folder/logs/long-worker.log" # --wait_until="Listening on var-www-$app-dokos-bench-folder:long"
ynh_systemctl --service=$app-frappe-short-worker --action="restart" --log_path="$install_dir/dokos-bench-folder/logs/short-worker.log" # --wait_until="Listening on var-www-$app-dokos-bench-folder:short"
ynh_systemctl --service=$app-frappe-schedule --action="restart" --log_path="systemd" --wait_until="Started dokos-frappe-schedule.service - "
systemctl restart "$app-workers.target" --quiet

ynh_systemctl --service=$app-frappe-web --action="restart" --log_path="systemd" --wait_until="Started dokos-frappe-web.service - "
ynh_systemctl --service=$app-node-socketio --action="restart" --log_path="$install_dir/dokos-bench-folder/logs/node-socketio.log" # --wait_until="Realtime service listening on"
systemctl restart "$app-web.target" --quiet

systemctl restart "$app.target" --quiet

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading NGINX web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# SCHEDULER
#=================================================
pushd $install_dir/dokos-bench-folder
	ynh_script_progression "Enabling Scheduler..."

	# Enable and resume the scheduler for the site

    ynh_exec_as_app PATH=$install_dir/bin:$PATH bench --site $domain scheduler enable && \
    ynh_exec_as_app PATH=$install_dir/bin:$PATH bench --site $domain scheduler resume && \

    ynh_script_progression "Upgrade website."

    # Updates the site's state to the current available apps : Run Application Patches, Synchronize Database Schema and Background Jobs,
    # Synchronize Fixtures, Synchronize Dashboards, Desktop Icons and Web Pages, Updates Translations, Rebuild Search Index for all routes
	ynh_exec_as_app PATH=$install_dir/bin:$PATH bench --site $domain migrate

    ynh_script_progression "Deactivate maintenance mode."

	# Deactivate maintenance mode.
	ynh_exec_as_app PATH=$install_dir/bin:$PATH bench --site $domain set-maintenance-mode off

popd

# Now to make sure the environment is fully setup
chmod 750 "$install_dir"
chown -R $app: "$install_dir"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading NGINX web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# KEEP LOGROTATE
#=================================================
ynh_script_progression "Upgrading logrotate configuration..."

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate "$install_dir/dokos-bench-folder/logs/redis-cache.log"
ynh_config_add_logrotate "$install_dir/dokos-bench-folder/logs/redis-queue.log"
ynh_config_add_logrotate "$install_dir/dokos-bench-folder/logs/default-worker.log"
ynh_config_add_logrotate "$install_dir/dokos-bench-folder/logs/long-worker.log"
ynh_config_add_logrotate "$install_dir/dokos-bench-folder/logs/short-worker.log"
ynh_config_add_logrotate "$install_dir/dokos-bench-folder/logs/schedule.log"
ynh_config_add_logrotate "$install_dir/dokos-bench-folder/logs/web.log"
ynh_config_add_logrotate "$install_dir/dokos-bench-folder/logs/node-socketio.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
